# Generated by Django 3.1.5 on 2021-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
                ('guid', models.CharField(max_length=255, verbose_name='guid')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('author_email', models.CharField(max_length=255, verbose_name='author email')),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='keywords')),
                ('version', models.CharField(max_length=50, verbose_name='version')),
                ('maintainer', models.CharField(blank=True, max_length=50, null=True, verbose_name='maintainer')),
                ('maintainer_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='mainteiner email')),
            ],
        ),
    ]
