# Generated by Django 3.1.5 on 2021-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypilogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='package',
            name='author_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='author email'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
